### ISSUE TITLE
Scanned Abbott Freestyle Libre reading should be a CGM entry instead of SMBG

### ISSUE THREAD

**Issue by mrinnetmaki** [tidepool-org/uploader#1141]
Currently the Uploader treats scanned entries (readings that are shown when manually swiping the NFC tag with the reader device) as SMBG entries.

Would it not be more logical to treat them as CGM entries instead? They are, after all, measurements of glucose in subcutaneous tissue rather than blood glucose.

**Comment by mrinnetmaki** [comment]
If it helps, 'scanned' was added as a SMBG subtype in https://github.com/tidepool-org/uploader/pull/804/commits/bb8439dae45147ff02f2caf7a44a5ed4a6aa14a9

**Comment by gniezen** [comment]
Hi @mrinnetmaki , we are indeed using `scanned` to disambiguate it from other SMBG values, like `manual` (measured using a BG meter), and `linked` (received from pump linked to a meter)

The Tidepool data model does not have a `CGM` record type, but uses `cbg` and `smbg` records. I realise that's not ideal, but I'd point out that both CGM (interstitial fluid) and  BG meters provide an estimate of actual blood glucose levels.

In this instance we consider Libre scanned entries to be "self-monitored" BG values instead of "continuous" BG values.

**Comment by mrinnetmaki** [comment]
Thanks for the explanation! I indeed had read `cbg` to equal CGM data, but the explanation helps.

As we historically used to calibrate CGM's based on glucometer readings, but never vice versa, I've grown to interpret SMBG readings as the "more reliable ones" and therefore want to display them separately.

But as mentioned, the `scanned` tag helps make the distinction. Thanks again!
