### ISSUE TITLE
the error on uploding

### ISSUE THREAD

**Issue by pauloved** [tidepool-org/uploader#1254]
Request URL: `https://api.tidepool.org/dataservices/v1/users/b986cc0fb3/datasets`
Request Payload `{"type":"upload","computerTime":"2020-07-15T14:39:01","time":"2020-07-15T14:39:00+07:00","timezoneOffset":420,"conversionOffset":0,"timezone":"Asia/Harbin","timeProcessing":"across-the-board-timezone","version":"2.28.1","deviceTags":["bgm"],"deviceTime":"2020-07-15T10:17:53","deviceManufacturers":["Roche"],"deviceModel":1,"deviceSerialNumber":"sdsdgdfdg","deviceId":"sdsgddgde","client":{"name":"org.tidepool.uploader","version":"2.28.1","private":{"os":"win32-x64-6.1.7601"}},"deduplicator":{"name":"org.tidepool.deduplicator.device.deactivate.hash"}}` 

Response `{"code":"type-not-string","title":"type is not string","detail":"type is not string, but float64","source":{"pointer":"/deviceModel"},"meta":{"type":"upload"}}`

whats wrong with this !!
help me thanks!

**Comment by gniezen** [comment]
Hi @pauloved ! The error response is saying that `deviceModel` is not a string. I can see from your request URL that you have the `deviceModel` set to `1`, which would explain why you're getting that error.

Here are more details on what should be in the `upload` record: https://developer.tidepool.org/data-model/device-data/types/upload.html

For development, please use the integration server instead of our production servers. You can do this by setting the environment variables as in https://github.com/tidepool-org/uploader/blob/master/config/integration.sh, or you can right-click on the login screen and select the Integration server.

**Comment by pauloved** [comment]
> Hi @pauloved ! The error response is saying that `deviceModel` is not a string. I can see from your request URL that you have the `deviceModel` set to `1`, which would explain why you're getting that error.
> 
> Here are more details on what should be in the `upload` record: https://developer.tidepool.org/data-model/device-data/types/upload.html
> 
> For development, please use the integration server instead of our production servers. You can do this by setting the environment variables as in https://github.com/tidepool-org/uploader/blob/master/config/integration.sh, or you can right-click on the login screen and select the Integration server.

thanks @gniezen  should i register a new account for the Integration server ?

**Comment by pauloved** [comment]
> Hi @pauloved ! The error response is saying that `deviceModel` is not a string. I can see from your request URL that you have the `deviceModel` set to `1`, which would explain why you're getting that error.
> 
> Here are more details on what should be in the `upload` record: https://developer.tidepool.org/data-model/device-data/types/upload.html
> 
> For development, please use the integration server instead of our production servers. You can do this by setting the environment variables as in https://github.com/tidepool-org/uploader/blob/master/config/integration.sh, or you can right-click on the login screen and select the Integration server.

hi @gniezen  we want to add a new device on uploader, 
so how we to add a deviceManufacturers, 
now the error Response  show :
![image](https://user-images.githubusercontent.com/20351530/87631839-c0016880-c76a-11ea-8f39-4290bbc7eba3.png)
 this is the request
url:`https://dev-api.tidepool.org/dataservices/v1/datasets/b5ccbde473daae3c0092feefb0a2dc73/data`,
request payload: `[{"time":"2020-07-15T21:43:06.000Z","timezoneOffset":-480,"clockDriftOffset":0,"conversionOffset":0,"deviceTime":"2020-07-15T15:04:05","type":"smbg","value":200,"units":"mg/dL","payload":{"logIndices":[2]}}]`
we use the dev-server  becasue we dont konw the integration server`s account!

**Comment by pauloved** [comment]
> > Hi @pauloved ! The error response is saying that `deviceModel` is not a string. I can see from your request URL that you have the `deviceModel` set to `1`, which would explain why you're getting that error.
> > Here are more details on what should be in the `upload` record: https://developer.tidepool.org/data-model/device-data/types/upload.html
> > For development, please use the integration server instead of our production servers. You can do this by setting the environment variables as in https://github.com/tidepool-org/uploader/blob/master/config/integration.sh, or you can right-click on the login screen and select the Integration server.
> 
> hi @gniezen we want to add a new device on uploader,
> so how we to add a deviceManufacturers,
> now the error Response show :
> ![image](https://user-images.githubusercontent.com/20351530/87631839-c0016880-c76a-11ea-8f39-4290bbc7eba3.png)
> this is the request
> url:`https://dev-api.tidepool.org/dataservices/v1/datasets/b5ccbde473daae3c0092feefb0a2dc73/data`,
> request payload: `[{"time":"2020-07-15T21:43:06.000Z","timezoneOffset":-480,"clockDriftOffset":0,"conversionOffset":0,"deviceTime":"2020-07-15T15:04:05","type":"smbg","value":200,"units":"mg/dL","payload":{"logIndices":[2]}}]`
> we use the dev-server becasue we dont konw the integration server`s account!

add the error pic 
![image](https://user-images.githubusercontent.com/20351530/87632144-5897e880-c76b-11ea-89a4-cb924bd20c06.png)

**Comment by gniezen** [comment]
You should just be able to create an account on the int server, but using the dev server is also fine (although it may be less stable at times, as we're using it for QA testing).

If you let me know what device you're trying to add, I can have a look at if it's currently on our roadmap?

Are you sending up the `smbg` record separately? There seem to be quite a few fields missing, e.g. `deviceId` and `uploadId`, which would explain why you're getting an error back. Are you using the Uploader code, or are you sending these requests manually? If you're not intending on using the Uploader but just want to send data directly to our API, please send me an e-mail at gerrit@tidepool.org so that we can send you the API docs.

**Comment by pauloved** [comment]
> 您应该只能够在int服务器上创建一个帐户，但是使用开发服务器也可以（尽管有时它可能不稳定，因为我们正在使用它进行质量检查）。
> 
> 如果您让我知道您要添加的设备，那么我可以看看它当前是否在我们的路线图中？
> 
> 您是否要分别发送`smbg`记录？似乎缺少很多字段，例如`deviceId`和`uploadId`，这将解释为什么您会收到错误提示。请参阅此处的必填字段：[https](https://developer.tidepool.org/data-model/device-data/types/smbg.html) : [//developer.tidepool.org/data-model/device-data/types/smbg.html](https://developer.tidepool.org/data-model/device-data/types/smbg.html)
> 
> 您使用的是Uploader代码，还是手动发送这些请求？如果您不打算使用Uploader，而只想直接将数据发送到我们的API，请给我发送电子邮件[gerrit@tidepool.org，](mailto:gerrit@tidepool.org)以便我们向您发送API文档。

we are using Uploader code ,  we haven't contacted tidepool yet, we want add a device named as WeiTai  ,so  what should we do except coding ？

**Comment by gniezen** [comment]
If the WeiTai device uploads via a USB cable, adding it to the Uploader is the way to go. If you submit your code as a pull request, we can do a code review, and if it passes our QA testing, we can merge it in to the Uploader code base.

**Comment by pauloved** [comment]
> If the WeiTai device uploads via a USB cable, adding it to the Uploader is the way to go. If you submit your code as a pull request, we can do a code review, and if it passes our QA testing, we can merge it in to the Uploader code base.

hi @gniezen  ,In development, how do I get the last upload record and then upload the latest record？
if I upload the same data in basal, then I get two identical data, and the total amount is superimposed

**Comment by gniezen** [comment]
To get the last upload record, use https://github.com/tidepool-org/uploader/blob/master/lib/core/api.js#L650

An example of how that is used: https://github.com/tidepool-org/uploader/blob/master/lib/drivers/medtronic/medtronicDriver.js#L1094-L1100

When uploading, make sure to send `dataservices` as the final parameter, so that it uploads via our newer platform API (which does better deduplication of identical data): https://github.com/tidepool-org/uploader/blob/master/lib/drivers/medtronic/medtronicDriver.js#L1752

**Comment by pauloved** [comment]
> To get the last upload record, use https://github.com/tidepool-org/uploader/blob/master/lib/core/api.js#L650
> 
> An example of how that is used: https://github.com/tidepool-org/uploader/blob/master/lib/drivers/medtronic/medtronicDriver.js#L1094-L1100
> 
> When uploading, make sure to send `dataservices` as the final parameter, so that it uploads via our newer platform API (which does better deduplication of identical data): https://github.com/tidepool-org/uploader/blob/master/lib/drivers/medtronic/medtronicDriver.js#L1752

hi @gniezen , we add our device in jellyfish API.  is ok ?

**Comment by gniezen** [comment]
The Jellyfish API is deprecated and will be removed in the near future, so I would highly recommend using the platform API (with the `dataservices` parameter). The platform API has much better data validation, so you can be more confident that the data being uploaded is correct.
