### ISSUE TITLE
Upload Failed with Contour Next Link 2.4 and Linux

### ISSUE THREAD

**Issue by ceranco** [tidepool-org/uploader#1312]
Hello,

I'm trying to run the program on Linux Mint 19.3.
I've succeeded in building and running the app by installing the dependencies specified in https://github.com/tidepool-org/uploader/issues/952#issuecomment-530300292 and running `yarn && yarn run build`.

I run the program by executing `yarn run start` and can successfully login, but when I try to upload data, I get the following:

> 
> Upload Failed: Something went wrong during device upload 
> Hide details
> Details: cannot open device with vendor id 0x1a79 and product id 0x6210 | UTC Time: 2020-09-15T12:35:42+03:00 | Name: Error | Code: E_DEVICE_UPLOAD | undefined: [object Object] | Stack Trace: new HID, connect, new Promise, connect, MM600SeriesDriver.value, Object.connect, configs.debug.async.waterfall.result, nextTask  

Do you know why this might happen?

**Comment by ceranco** [comment]
To make sure that my Contour isn't faulty, I've tried running the app on a windows computer, which worked with no problems.

**Comment by loudestnoise** [comment]
Hi @ceranco, Dave from the Tidepool Support team here. Do you know what version of Tidepool Uploader you are running on your computer? We recently (9/15/20) required a new minimum version of Tidepool Uploader 2.31.0, so I'm wondering if that could be the issue.

From the error message though, it seems like it's having trouble communicating with your Contour NEXT Link 2.4 Meter. I remember seeing on the #952 issue that Uploader has to run as root otherwise it can't access data from the connected devices. Could that possibly be what's happening here?

**Comment by loudestnoise** [comment]
and you may also look into using Tidepool Uploader on Linux via Docker as documented here in this pull request - https://github.com/tidepool-org/uploader/pull/1244

**Comment by ceranco** [comment]
Hi Dave, running as root fixed it!

I can successfully login and upload data when running:
```
sudo yarn run start --no-sandbox
```
The `--no-sandbox` is needed, otherwise it fails with
> [35374:0916/192235.867698:FATAL:electron_main_delegate.cc(211)] Running as root without --no-sandbox is not supported.

Thank you very much for the quick response :smile:

**Comment by gniezen** [comment]
Hi @ceranco ! If you don't want to run Uploader as root in future, I think what you need to do is to add the udev rules as per the note in https://github.com/tidepool-org/uploader#docker-for-linux

**Comment by ceranco** [comment]
Thanks @gniezen, that's good to know!
I have no problem running as root currently, but if I ever need to, I will be sure to try your suggestion :smile:
