### ISSUE TITLE
Abbott Freestyle support on OS X

### ISSUE THREAD

**Issue by seanknox** [tidepool-org/uploader#282]
Hi,

I'd like to work on adding OS X support to the Abbott (Freestyle) driver but to be honest, I'm not sure where to start. What I know so far:
- The upload product page shows that Abbott devices are only supported on Windows, and
- http://developer.tidepool.io/serial-ports/ mentions that Abbott devices use a custom serial cable.
- Some information about the Freestyle protocol is available [here](http://www.flupzor.nl/protocol.html) and the ABNF protocol [here](ftp://ftp.rfc-editor.org/in-notes/std/std68.txt)

Since are no unit tests currently, I thought creating some might be useful for the project and as a teaching tool for myself. What do you think? Are there any Tidepool documentation or other resources that would be useful on this subject?

**Comment by gniezen** [comment]
Hi Sean!

Sorry for the late response, I somehow missed this. The reason why we're not yet supporting Abbott devices on OS X is that there is no Mac USB serial driver available. More information is available on our Uploader backlog: https://trello.com/c/YZX70Mch

The USB-serial chip is built into the cable (instead of the device itself) and uses the TI USB3410 chipset. TI only released an experimental version of a Mac driver, and that was last updated years ago. It seems the way to go is to develop a userspace driver using `chrome.usb`, with the TI code as a reference. 

Would you feel comfortable working on something like this?

Cheers,
Gerrit

**Comment by seanknox** [comment]
Hey Gerrit,

No worries. I pledge to at least take a look. Will check out the trello
board. Thanks!

**Comment by gniezen** [comment]
Hi @FelixGV ! I'll see if I can make that card public again, it's probably been moved to a private board. I'm actually currently working on user-space drivers for macOS, as Apple has been making it really difficult to install kernel extensions since the release of High Sierra.

Once the mechanism to use user-space drivers in the Uploader is in place, it should be easier to add a user-space driver for Abbott meters. I have actually already created a user-space driver for Abbott meters [on my personal GitHub account](https://github.com/gniezen/webusb-uploader/blob/master/webusb.js), so it shouldn't be too hard to add it to the Uploader once I'm finished with the other drivers.

In the meanwhile, while I haven't tested it myself, I do think Parallels should work. Let me know if it works for you!

**Comment by pazaan** [comment]
Hey @FelixGV - those Trello boards have been made public now, so you should be able to see that card again.
Also, as far as Parallels goes - I can successfully upload other USB-based diabetes devices on Win10 running in Parallels on my Mac. I don't have a Freestyle, so I can't speak for that device specifically, but I see no reason why it _shouldn't_ work.

**Comment by gniezen** [comment]
I'm going to close this ticket, as we now support uploading Abbott FreeStyle Lite and Freedom Lite meters using the [EZSync002B](https://purenitetech.com/product/ezsync002b/) cable.
